clearvars;
close all force;
clc;

%% ============================================================
% PHYLUM C-ASCA + oMEDA GROUND-TRUTH ERROR
%
% For each simulation repetition, this script:
%   1. reads one combined 10-method CSV file;
%   2. runs C-ASCA;
%   3. extracts the C-ASCA consensus representation B + C(B);
%   4. calculates oMEDA vectors for the 10 input methods and C-ASCA;
%   5. calculates sign-invariant squared error relative to ground truth;
%   6. calculates Low, High and Full errors;
%   7. summarizes errors as mean ± standard deviation across repetitions.
%
% Method codes in the CSV:
%   1  Raw Data
%   2  CLR+1
%   3  CLR-MR
%   4  TSS
%   5  Rarefaction
%   6  CSS
%   7  edgeR-TMM
%   8  DESeq2
%   9  ALDEx2
%   10 ANCOM
%
% The additional evaluated representation is:
%   11 C-ASCA
%% ============================================================

%% ============================================================
% USER SETTINGS
%% ============================================================

analysisLevel = "genus";

expectedMethods = 10;
expectedRowsPerMethod = 300;
samplesPerGroup = 150;
subsetPerGroup = 50;

% Add or remove scenarios as needed.
%
% The second path is an editable placeholder. If the folder does not exist,
% the script skips it and continues with the available scenario(s).
scenarioConfigs = struct( ...
    'Name', { ...
        "Positive", ...
        "Unequal-depth Positive" ...
    }, ...
    'Root', { ...
        'D:\Genus\TrueUn', ...
        'D:\Genus\True' ...
    }, ...
    'Pattern', { ...
        'phylum_10_methods_combined_rep*.csv', ...
        'phylum_10_methods_combined_rep*.csv' ...
    } ...
);

masterOutputDir = fullfile( ...
    'D:\Genus', ...
    'CASCA_oMEDA_Error_Summary' ...
);

if ~exist(masterOutputDir, 'dir')
    mkdir(masterOutputDir);
end

%% ============================================================
% METHOD NAMES
%% ============================================================

methodNames = [
    "Raw Data"
    "CLR+1"
    "CLR-MR"
    "TSS"
    "Rarefaction"
    "CSS"
    "edgeR-TMM"
    "DESeq2"
    "ALDEx2"
    "ANCOM"
    "C-ASCA"
];

nEvaluatedMethods = numel(methodNames);

subsetNames = [
    "Low"
    "High"
    "Full"
];

nSubsets = numel(subsetNames);

%% ============================================================
% PHYLUM TAXA LABELS
%% ============================================================

switch lower(analysisLevel)

    case "genus"

lab = {"Bifidobacterium","Butyricimonas","Odoribacter","Paraprevotella", ...
      "Bacteroides","Parabacteroides","Prevotella","Unknown1","Unknown2", ...
      "Unknown3","Clostridium","Unknown4","Unknown5","Ruminococcus","Anaerostipes", ...
      "Blautia","Coprococcus","Dorea","Lachnospira","Roseburia","Unknown6", ...
      "Unknown7","Unknown8","Unknown9","Faecalibacterium","Oscillospira", ...
      "Ruminococcus_dup","Dialister","Unknown10","Unknown11","Unknown12","Sutterella", ...
      "Escherichia","Klebsiella","Haemophilus","Akkermansia"};

    otherwise
        error('This script is currently configured for phylum data.');

end

%% ============================================================
% GROUND-TRUTH VECTOR
%
% Columns:
%   1 = Healthy/Control
%   2 = Sick/Case
%% ============================================================


groundTruthAbundance = [
    0.15, 0.38          % Bifidobacterium
    0.60, 0.60          % Butyricimonas
    1.50, 1.50          % Odoribacter
    1.60, 0.00          % Paraprevotella
   12.20, 26.00         % Bacteroides
    4.10, 0.01          % Parabacteroides
   30.80, 0.02          % Prevotella
    2.30, 11.00         % Unknown1
    0.14, 0.70          % Unknown2
    1.21, 1.00          % Unknown3
    0.18, 0.14          % Clostridium
    0.32, 1.00          % Unknown4
    3.31, 0.15          % Unknown5
    0.63, 0.30          % Ruminococcus
    0.17, 0.00          % Anaerostipes
    0.34, 0.30          % Blautia
    1.08, 3.00          % Coprococcus
    0.14, 0.14          % Dorea
    2.15, 0.02          % Lachnospira
    2.37, 0.50          % Roseburia
    0.033, 1.00         % Unknown6
    0.47, 0.14          % Unknown7
    0.34, 2.00          % Unknown8
    5.46, 4.80          % Unknown9
    3.47, 0.00          % Faecalibacterium
    6.42, 0.20          % Oscillospira
    4.25, 0.05          % Ruminococcus_dup
    2.81, 5.00          % Dialister
    0.36, 3.00          % Unknown10
    1.02, 2.70          % Unknown11
    0.83, 0.80          % Unknown12
    1.80, 8.00          % Sutterella
    0.31, 0.22          % Escherichia
    1e-6, 0.00          % Klebsiella
    0.17, 0.31          % Haemophilus
    7.10, 1.23          % Akkermansia
];
 

GTP = groundTruthAbundance - mean(groundTruthAbundance, 2);

groundTruth = ...
      sign(GTP(:,2)) .* (GTP(:,2).^2) ...
    - sign(GTP(:,1)) .* (GTP(:,1).^2);

groundTruth = groundTruth(:);

groundTruthNorm = norm(groundTruth);

if groundTruthNorm < eps
    error('The ground-truth vector has zero or near-zero norm.');
end

GT = groundTruth / groundTruthNorm;

if numel(GT) ~= numel(lab)
    error( ...
        'The ground-truth vector and taxa labels have different lengths.' ...
    );
end

%% ============================================================
% STORAGE ACROSS SCENARIOS
%% ============================================================

scenarioResults = struct([]);

%% ============================================================
% PROCESS EACH SCENARIO
%% ============================================================

for scenarioIndex = 1:numel(scenarioConfigs)

    scenarioName = string(scenarioConfigs(scenarioIndex).Name);
    dataRoot = scenarioConfigs(scenarioIndex).Root;
    filePattern = scenarioConfigs(scenarioIndex).Pattern;

    fprintf('\n');
    fprintf('============================================================\n');
    fprintf('SCENARIO: %s\n', scenarioName);
    fprintf('ROOT: %s\n', dataRoot);
    fprintf('============================================================\n');

    if ~isfolder(dataRoot)
        warning( ...
            'Scenario folder does not exist and will be skipped: %s', ...
            dataRoot ...
        );
        continue;
    end

    csvFiles = dir( ...
        fullfile(dataRoot, '**', filePattern) ...
    );

    if isempty(csvFiles)
        warning( ...
            'No files matching "%s" were found under %s.', ...
            filePattern, ...
            dataRoot ...
        );
        continue;
    end

    % Sort by repetition number rather than lexicographic filename only.
    repNumbersForSort = nan(numel(csvFiles), 1);

    for q = 1:numel(csvFiles)
        token = regexp(csvFiles(q).name, 'rep(\d+)', 'tokens', 'once');

        if isempty(token)
            repNumbersForSort(q) = q;
        else
            repNumbersForSort(q) = str2double(token{1});
        end
    end

    [~, sortOrder] = sort(repNumbersForSort);
    csvFiles = csvFiles(sortOrder);
    repNumbersForSort = repNumbersForSort(sortOrder);

    numberOfFiles = numel(csvFiles);

    fprintf('Found %d CSV files.\n', numberOfFiles);

    if numberOfFiles ~= 100
        warning( ...
            'Expected 100 files for %s, but found %d.', ...
            scenarioName, ...
            numberOfFiles ...
        );
    end

    scenarioOutputDir = fullfile( ...
        masterOutputDir, ...
        matlab.lang.makeValidName(char(scenarioName)) ...
    );

    if ~exist(scenarioOutputDir, 'dir')
        mkdir(scenarioOutputDir);
    end

    % Dimensions:
    % repetitions × evaluated methods × subsets
    errorArray = nan( ...
        numberOfFiles, ...
        nEvaluatedMethods, ...
        nSubsets ...
    );

    orientationArray = strings( ...
        numberOfFiles, ...
        nEvaluatedMethods, ...
        nSubsets ...
    );

    analysisCompleted = false(numberOfFiles, 1);
    failureMessage = strings(numberOfFiles, 1);
    repetitionNumber = repNumbersForSort(:);
    inputFileName = strings(numberOfFiles, 1);
    resultFileName = strings(numberOfFiles, 1);

    %% ========================================================
    % PROCESS EACH REPETITION
    %% ========================================================

    for fileIndex = 1:numberOfFiles

        close all force;
        drawnow;

        currentFile = fullfile( ...
            csvFiles(fileIndex).folder, ...
            csvFiles(fileIndex).name ...
        );

        repNumber = repetitionNumber(fileIndex);
        inputFileName(fileIndex) = string(currentFile);

        fprintf('\nProcessing %s, repetition %03d (%d of %d)\n', ...
            scenarioName, ...
            repNumber, ...
            fileIndex, ...
            numberOfFiles ...
        );

        try

            %% =================================================
            % READ AND VALIDATE TABLE
            %% =================================================

            Datos = readtable( ...
                currentFile, ...
                'VariableNamingRule', 'preserve' ...
            );

            expectedTotalRows = ...
                expectedMethods * expectedRowsPerMethod;

            if height(Datos) ~= expectedTotalRows
                error( ...
                    ['Expected %d rows for 10 methods × 300 observations, ' ...
                     'but found %d.'], ...
                    expectedTotalRows, ...
                    height(Datos) ...
                );
            end

            requiredMetadataColumns = [
                "Methods"
                "Groups"
                "observation"
            ];

            variableNames = string(Datos.Properties.VariableNames);

            missingColumns = requiredMetadataColumns( ...
                ~ismember(requiredMetadataColumns, variableNames) ...
            );

            if ~isempty(missingColumns)
                error( ...
                    'Missing required columns: %s', ...
                    strjoin(cellstr(missingColumns), ', ') ...
                );
            end

            taxaColumnCount = width(Datos) - 3;

            if taxaColumnCount ~= numel(lab)
                error( ...
                    'Expected %d taxa columns, but found %d.', ...
                    numel(lab), ...
                    taxaColumnCount ...
                );
            end

            Xoriginal = table2array( ...
                Datos(:, 1:taxaColumnCount) ...
            );

            if ~isnumeric(Xoriginal)
                error('The taxa columns are not numeric.');
            end

            if any(~isfinite(Xoriginal), 'all')
                error('The taxa matrix contains NaN or Inf values.');
            end

            taxaNames = string( ...
                Datos.Properties.VariableNames(1:taxaColumnCount) ...
            );

            %% =================================================
            % METHODS
            %% =================================================

            if isnumeric(Datos.Methods)
                MethodCode = double(Datos.Methods);
            else
                MethodCode = str2double(string(Datos.Methods));
            end

            MethodCode = MethodCode(:);

            if any(isnan(MethodCode)) || ...
                    any(~ismember(MethodCode, 1:expectedMethods))
                error('Datos.Methods must contain numeric codes 1:10.');
            end

            expectedMethodSequence = repelem( ...
                (1:expectedMethods)', ...
                expectedRowsPerMethod ...
            );

            if ~isequal(MethodCode, expectedMethodSequence)
                error( ...
                    ['Rows must be ordered in 10 consecutive method blocks, ' ...
                     'with 300 observations per block.'] ...
                );
            end

            methodCounts = arrayfun( ...
                @(k) sum(MethodCode == k), ...
                1:expectedMethods ...
            );

            if any(methodCounts ~= expectedRowsPerMethod)
                error( ...
                    'Every method must contain exactly 300 rows.' ...
                );
            end

            %% =================================================
            % GROUPS
            %% =================================================

            GroupsOriginal = Datos.Groups;
            Group = nan(height(Datos), 1);

            if isnumeric(GroupsOriginal)

                numericGroups = double(GroupsOriginal);

                Group(numericGroups == 1) = -1;
                Group(numericGroups == 2) = 1;

                if any(~ismember(numericGroups, [1 2]))
                    error('Numeric Groups must contain only 1 and 2.');
                end

                Groups = string(numericGroups);

            else

                Groups = string(GroupsOriginal);

                controlMask = ...
                    strcmpi(Groups, "Healthy") | ...
                    strcmpi(Groups, "Control");

                caseMask = ...
                    strcmpi(Groups, "Case") | ...
                    strcmpi(Groups, "Sick") | ...
                    strcmpi(Groups, "Dysbiosis");

                Group(controlMask) = -1;
                Group(caseMask) = 1;

                if any(~(controlMask | caseMask))
                    unknownGroups = unique(Groups(~(controlMask | caseMask)));

                    error( ...
                        'Unrecognized group labels: %s', ...
                        strjoin(cellstr(unknownGroups), ', ') ...
                    );
                end

            end

            %% =================================================
            % OBSERVATION
            %% =================================================

            if isnumeric(Datos.observation)
                observation = double(Datos.observation);
            else
                observation = str2double(string(Datos.observation));
            end

            observation = observation(:);

            expectedObservationSequence = repmat( ...
                (1:expectedRowsPerMethod)', ...
                expectedMethods, ...
                1 ...
            );

            if ~isequal(observation, expectedObservationSequence)
                error( ...
                    ['observation must run from 1 to 300 within every ' ...
                     'method block.'] ...
                );
            end

            %% =================================================
            % FIXED GROUP VECTOR WITHIN ONE METHOD BLOCK
            %% =================================================

            yFull = [
                -ones(samplesPerGroup, 1)
                 ones(samplesPerGroup, 1)
            ];

            for methodIndex = 1:expectedMethods

                idxMethod = MethodCode == methodIndex;

                if ~isequal(Group(idxMethod), yFull)
                    error( ...
                        ['Method %d does not contain Healthy observations ' ...
                         '1:150 followed by Sick observations 151:300.'], ...
                        methodIndex ...
                    );
                end

            end

            %% =================================================
            % RAW DEPTH AND LOW/HIGH SUBSETS
            %
            % Low  = 50 lowest-depth samples per biological group
            % High = 50 highest-depth samples per biological group
            % Full = all 150 + 150 samples
            %% =================================================

            rawBlock = Xoriginal(MethodCode == 1, :);
            rawDepth = sum(rawBlock, 2);

            if any(rawDepth <= 0)
                error('Raw sequencing depth contains zero values.');
            end

            controlRows = (1:samplesPerGroup)';
            caseRows = (samplesPerGroup + 1 : 2*samplesPerGroup)';

            [~, controlOrder] = sort(rawDepth(controlRows), 'ascend');
            [~, caseOrder] = sort(rawDepth(caseRows), 'ascend');

            idxLow = [
                controlRows(controlOrder(1:subsetPerGroup))
                caseRows(caseOrder(1:subsetPerGroup))
            ];

            idxHigh = [
                controlRows(controlOrder(end-subsetPerGroup+1:end))
                caseRows(caseOrder(end-subsetPerGroup+1:end))
            ];

            idxFull = (1:expectedRowsPerMethod)';

            subsetIndices = {
                idxLow
                idxHigh
                idxFull
            };

            yLow = [
                -ones(subsetPerGroup, 1)
                 ones(subsetPerGroup, 1)
            ];

            yHigh = yLow;

            subsetGroupVectors = {
                yLow
                yHigh
                yFull
            };

            %% =================================================
            % BLOCK-WISE SSQ NORMALIZATION FOR C-ASCA
            %% =================================================

            Xscaled = Xoriginal;
            depthRepeated = repmat(rawDepth, expectedMethods, 1);
            rankedDepth = depthRepeated;

            for methodIndex = 1:expectedMethods

                idx = ...
                    (methodIndex - 1) * expectedRowsPerMethod + 1 : ...
                    methodIndex * expectedRowsPerMethod;

                block = Xoriginal(idx, :);

                blockCentered = preprocess2D( ...
                    block, ...
                    'Preprocessing', 1 ...
                );

                blockSSQ = sum(blockCentered(:).^2);

                if blockSSQ <= eps
                    error( ...
                        'Method block %d has zero or near-zero SSQ.', ...
                        methodIndex ...
                    );
                end

                Xscaled(idx, :) = block / sqrt(blockSSQ);
                rankedDepth(idx) = tiedrank(depthRepeated(idx));

            end

            %% =================================================
            % RUN C-ASCA
            %% =================================================

            F = [
                MethodCode, ...
                Group, ...
                observation, ...
                rankedDepth ...
            ];

            [T, parglmStruct] = parglm( ...
                Xscaled, ...
                F, ...
                'Preprocessing', 1, ...
                'Model', [1 2], ...
                'Ordinal', [0 0 0 1], ...
                'Random', [0 0 1 0], ...
                'Nested', [2,3] ...
            );

            if height(T) >= 5
                T.Source(2:5) = {
                    'Method'
                    'Group'
                    'observation'
                    'depth'
                };
            end

            ascao = asca(parglmStruct);
            model = ascao;

            %% =================================================
            % EXTRACT C-ASCA CONSENSUS B + C(B)
            %% =================================================

            if ~isfield(ascao, 'factors') || numel(ascao.factors) < 3
                error( ...
                    ['ascao.factors does not contain the expected Group and ' ...
                     'observation effects.'] ...
                );
            end

            consensusRepeated = ...
                ascao.factors{2}.matrix + ...
                ascao.factors{3}.matrix;

            expectedConsensusRows = ...
                expectedMethods * expectedRowsPerMethod;

            if size(consensusRepeated, 1) ~= expectedConsensusRows
                error( ...
                    ['Expected %d rows in repeated C-ASCA consensus, ' ...
                     'but found %d.'], ...
                    expectedConsensusRows, ...
                    size(consensusRepeated, 1) ...
                );
            end

            nTaxa = size(consensusRepeated, 2);

            consensus3D = reshape( ...
                consensusRepeated, ...
                expectedRowsPerMethod, ...
                expectedMethods, ...
                nTaxa ...
            );

            % Average the repeated copies across method blocks.
            Xconsensus = reshape( ...
                mean(consensus3D, 2, 'omitnan'), ...
                expectedRowsPerMethod, ...
                nTaxa ...
            );

            %% =================================================
            % oMEDA VECTORS AND ERRORS
            %% =================================================

            Rall = nan(numel(GT), nEvaluatedMethods, nSubsets);
            errToGT = nan(nEvaluatedMethods, nSubsets);
            errToMinusGT = nan(nEvaluatedMethods, nSubsets);
            minError = nan(nEvaluatedMethods, nSubsets);
            selectedOrientation = strings(nEvaluatedMethods, nSubsets);

            for subsetIndex = 1:nSubsets

                idxSubset = subsetIndices{subsetIndex};
                ySubset = subsetGroupVectors{subsetIndex};

                % Ten original preprocessing methods.
                for methodIndex = 1:expectedMethods

                    methodRows = ...
                        (methodIndex - 1) * expectedRowsPerMethod + ...
                        idxSubset;

                    XmethodSubset = Xoriginal(methodRows, :);

                    rj = omedaPca( ...
                        XmethodSubset, ...
                        [], ...
                        XmethodSubset, ...
                        ySubset, ...
                        'VarsLabel', lab, ...
                        'Preprocessing', 1 ...
                    );

                    rj = rj(:);

                    if numel(rj) ~= numel(GT)
                        error( ...
                            ['oMEDA vector length mismatch for method %d, ' ...
                             'subset %s.'], ...
                            methodIndex, ...
                            subsetNames(subsetIndex) ...
                        );
                    end

                    rjNorm = norm(rj);

                    if rjNorm < eps
                        error( ...
                            ['oMEDA vector has zero norm for method %d, ' ...
                             'subset %s.'], ...
                            methodIndex, ...
                            subsetNames(subsetIndex) ...
                        );
                    end

                    Rall(:, methodIndex, subsetIndex) = rj / rjNorm;

                end

                % C-ASCA consensus representation.
                XconsensusSubset = Xconsensus(idxSubset, :);

                rjCASCA = omedaPca( ...
                    XconsensusSubset, ...
                    [], ...
                    XconsensusSubset, ...
                    ySubset, ...
                    'VarsLabel', lab, ...
                    'Preprocessing', 1 ...
                );

                rjCASCA = rjCASCA(:);
                rjCASCANorm = norm(rjCASCA);

                if rjCASCANorm < eps
                    error( ...
                        'C-ASCA oMEDA vector has zero norm for subset %s.', ...
                        subsetNames(subsetIndex) ...
                    );
                end

                Rall(:, nEvaluatedMethods, subsetIndex) = ...
                    rjCASCA / rjCASCANorm;

                % Sign-invariant squared error.
                Rsubset = Rall(:, :, subsetIndex);

                errToGT(:, subsetIndex) = ...
                    sum((Rsubset - GT).^2, 1)';

                errToMinusGT(:, subsetIndex) = ...
                    sum((Rsubset + GT).^2, 1)';

                minError(:, subsetIndex) = min( ...
                    errToGT(:, subsetIndex), ...
                    errToMinusGT(:, subsetIndex) ...
                );

                selectedOrientation( ...
                    errToGT(:, subsetIndex) <= ...
                    errToMinusGT(:, subsetIndex), ...
                    subsetIndex ...
                ) = "GT";

                selectedOrientation( ...
                    errToMinusGT(:, subsetIndex) < ...
                    errToGT(:, subsetIndex), ...
                    subsetIndex ...
                ) = "-GT";

            end

            errorArray(fileIndex, :, :) = minError;
            orientationArray(fileIndex, :, :) = selectedOrientation;

            %% =================================================
            % PER-REPETITION ERROR TABLE
            %% =================================================

            RepetitionErrors = table( ...
                methodNames, ...
                minError(:,1), ...
                minError(:,2), ...
                minError(:,3), ...
                selectedOrientation(:,1), ...
                selectedOrientation(:,2), ...
                selectedOrientation(:,3), ...
                'VariableNames', { ...
                    'Method', ...
                    'LowError', ...
                    'HighError', ...
                    'FullError', ...
                    'LowOrientation', ...
                    'HighOrientation', ...
                    'FullOrientation' ...
                } ...
            );

            outputMatFile = fullfile( ...
                scenarioOutputDir, ...
                sprintf( ...
                    'phylum_CASCA_oMEDA_errors_rep%03d.mat', ...
                    repNumber ...
                ) ...
            );

            outputCsvFile = fullfile( ...
                scenarioOutputDir, ...
                sprintf( ...
                    'phylum_CASCA_oMEDA_errors_rep%03d.csv', ...
                    repNumber ...
                ) ...
            );

            writetable(RepetitionErrors, outputCsvFile);

            save( ...
                outputMatFile, ...
                'T', ...
                'parglmStruct', ...
                'ascao', ...
                'model', ...
                'Xoriginal', ...
                'Xscaled', ...
                'Xconsensus', ...
                'F', ...
                'MethodCode', ...
                'Group', ...
                'Groups', ...
                'observation', ...
                'rawDepth', ...
                'idxLow', ...
                'idxHigh', ...
                'idxFull', ...
                'GT', ...
                'Rall', ...
                'errToGT', ...
                'errToMinusGT', ...
                'minError', ...
                'selectedOrientation', ...
                'RepetitionErrors', ...
                'methodNames', ...
                'subsetNames', ...
                'taxaNames', ...
                'lab', ...
                'currentFile', ...
                'repNumber', ...
                '-v7.3' ...
            );

            resultFileName(fileIndex) = string(outputMatFile);
            analysisCompleted(fileIndex) = true;

            fprintf('Completed repetition %03d.\n', repNumber);

        catch ME

            analysisCompleted(fileIndex) = false;
            failureMessage(fileIndex) = string(ME.message);

            warning( ...
                '%s repetition %03d failed: %s', ...
                scenarioName, ...
                repNumber, ...
                ME.message ...
            );

        end

    end

    %% ========================================================
    % SCENARIO SUMMARY: MEAN ± STANDARD DEVIATION
    %% ========================================================

    meanError = squeeze(mean(errorArray, 1, 'omitnan'));
    stdError = squeeze(std(errorArray, 0, 1, 'omitnan'));
    validN = squeeze(sum(~isnan(errorArray), 1));

    ScenarioSummary = table( ...
        methodNames, ...
        meanError(:,1), ...
        stdError(:,1), ...
        validN(:,1), ...
        meanError(:,2), ...
        stdError(:,2), ...
        validN(:,2), ...
        meanError(:,3), ...
        stdError(:,3), ...
        validN(:,3), ...
        'VariableNames', { ...
            'Method', ...
            'LowMean', ...
            'LowSD', ...
            'LowN', ...
            'HighMean', ...
            'HighSD', ...
            'HighN', ...
            'FullMean', ...
            'FullSD', ...
            'FullN' ...
        } ...
    );

    % Formatted text fields for direct inspection.
    ScenarioSummary.LowFormatted = compose( ...
        '%.3f ± %.3f', ...
        ScenarioSummary.LowMean, ...
        ScenarioSummary.LowSD ...
    );

    ScenarioSummary.HighFormatted = compose( ...
        '%.3f ± %.3f', ...
        ScenarioSummary.HighMean, ...
        ScenarioSummary.HighSD ...
    );

    ScenarioSummary.FullFormatted = compose( ...
        '%.3f ± %.3f', ...
        ScenarioSummary.FullMean, ...
        ScenarioSummary.FullSD ...
    );

    ScenarioSummary = movevars( ...
        ScenarioSummary, ...
        {'LowFormatted','HighFormatted','FullFormatted'}, ...
        'After', ...
        'Method' ...
    );

    summaryCsv = fullfile( ...
        scenarioOutputDir, ...
        'phylum_CASCA_oMEDA_mean_sd_summary.csv' ...
    );

    writetable(ScenarioSummary, summaryCsv);

    %% ========================================================
    % LONG-FORM REPETITION-LEVEL TABLE
    %% ========================================================

    totalLongRows = ...
        numberOfFiles * nEvaluatedMethods * nSubsets;

    longScenario = strings(totalLongRows, 1);
    longRep = nan(totalLongRows, 1);
    longMethod = strings(totalLongRows, 1);
    longSubset = strings(totalLongRows, 1);
    longError = nan(totalLongRows, 1);
    longOrientation = strings(totalLongRows, 1);

    rowCounter = 0;

    for r = 1:numberOfFiles
        for m = 1:nEvaluatedMethods
            for s = 1:nSubsets

                rowCounter = rowCounter + 1;

                longScenario(rowCounter) = scenarioName;
                longRep(rowCounter) = repetitionNumber(r);
                longMethod(rowCounter) = methodNames(m);
                longSubset(rowCounter) = subsetNames(s);
                longError(rowCounter) = errorArray(r,m,s);
                longOrientation(rowCounter) = ...
                    orientationArray(r,m,s);

            end
        end
    end

    RepetitionLevelErrors = table( ...
        longScenario, ...
        longRep, ...
        longMethod, ...
        longSubset, ...
        longError, ...
        longOrientation, ...
        'VariableNames', { ...
            'Scenario', ...
            'Repetition', ...
            'Method', ...
            'Subset', ...
            'MinimumSquaredError', ...
            'SelectedOrientation' ...
        } ...
    );

    longCsv = fullfile( ...
        scenarioOutputDir, ...
        'phylum_CASCA_oMEDA_repetition_level_errors.csv' ...
    );

    writetable(RepetitionLevelErrors, longCsv);

    %% ========================================================
    % ANALYSIS STATUS TABLE
    %% ========================================================

    AnalysisSummary = table( ...
        repetitionNumber, ...
        inputFileName, ...
        resultFileName, ...
        analysisCompleted, ...
        failureMessage, ...
        'VariableNames', { ...
            'Repetition', ...
            'InputFile', ...
            'ResultFile', ...
            'Completed', ...
            'FailureMessage' ...
        } ...
    );

    writetable( ...
        AnalysisSummary, ...
        fullfile( ...
            scenarioOutputDir, ...
            'analysis_status.csv' ...
        ) ...
    );

    save( ...
        fullfile( ...
            scenarioOutputDir, ...
            'scenario_complete_results.mat' ...
        ), ...
        'scenarioName', ...
        'errorArray', ...
        'orientationArray', ...
        'ScenarioSummary', ...
        'RepetitionLevelErrors', ...
        'AnalysisSummary', ...
        'methodNames', ...
        'subsetNames', ...
        'GT', ...
        '-v7.3' ...
    );

    scenarioResults(end+1).Name = scenarioName; %#ok<SAGROW>
    scenarioResults(end).Summary = ScenarioSummary;
    scenarioResults(end).Errors = errorArray;
    scenarioResults(end).OutputDir = string(scenarioOutputDir);

    fprintf('\nSummary for %s:\n', scenarioName);
    disp( ...
        ScenarioSummary(:, { ...
            'Method', ...
            'LowFormatted', ...
            'HighFormatted', ...
            'FullFormatted' ...
        }) ...
    );

end

%% ============================================================
% COMBINED POSITIVE + UNEQUAL-DEPTH POSITIVE TABLE
%% ============================================================

if isempty(scenarioResults)
    error('No scenario was successfully processed.');
end

if numel(scenarioResults) == 1

    CombinedSummary = scenarioResults(1).Summary(:, { ...
        'Method', ...
        'LowFormatted', ...
        'HighFormatted', ...
        'FullFormatted' ...
    });

    scenarioPrefix = matlab.lang.makeValidName( ...
        char(scenarioResults(1).Name) ...
    );

    CombinedSummary.Properties.VariableNames = { ...
        'Method', ...
        [scenarioPrefix '_Low'], ...
        [scenarioPrefix '_High'], ...
        [scenarioPrefix '_Full'] ...
    };

else

    Summary1 = scenarioResults(1).Summary;
    Summary2 = scenarioResults(2).Summary;

    CombinedSummary = table( ...
        methodNames, ...
        Summary1.LowFormatted, ...
        Summary1.HighFormatted, ...
        Summary1.FullFormatted, ...
        Summary2.LowFormatted, ...
        Summary2.HighFormatted, ...
        Summary2.FullFormatted, ...
        'VariableNames', { ...
            'Method', ...
            'Positive_Low', ...
            'Positive_High', ...
            'Positive_Full', ...
            'UnequalDepthPositive_Low', ...
            'UnequalDepthPositive_High', ...
            'UnequalDepthPositive_Full' ...
        } ...
    );
    close all;

end

combinedCsv = fullfile( ...
    masterOutputDir, ...
    'phylum_CASCA_oMEDA_combined_mean_sd_table.csv' ...
);

writetable(CombinedSummary, combinedCsv);

save( ...
    fullfile( ...
        masterOutputDir, ...
        'phylum_CASCA_oMEDA_all_scenarios.mat' ...
    ), ...
    'scenarioResults', ...
    'CombinedSummary', ...
    'methodNames', ...
    'subsetNames', ...
    'GT', ...
    '-v7.3' ...
);

fprintf('\n');
fprintf('============================================================\n');
fprintf('FINAL COMBINED MEAN ± SD TABLE\n');
fprintf('============================================================\n');
disp(CombinedSummary);
fprintf('Exported to:\n%s\n', combinedCsv);
fprintf('============================================================\n');
